### ISSUE TITLE
The predictor part regards the class 2 as class 12 mistakenly.

### ISSUE THREAD

**Issue by waterofsilence** [sniper0110/IntroductionToTensorflow2#1]
In the last part of this project,the predictor always regards the class 2 as class12 by mistake.This error also occurred in the teaching video,I found that it was not accidental. I randomly selected 10 pictures of class 2 , and all the pictures were classified as 12 class by the predictor. Was there an error in the process of loading the pictures?I suspect that there is a problem in the process of image reading by ImageDataGenerator. What should I do?Thank you!

**Comment by waterofsilence** [comment]
I have solved this problem.Focus on ImageDataGenerator and the flow_from_directory function.When we use the flow_from_directory,we should add the 'classes=class_category'.In fact,the class category is a list of the classes in the natural number order,[0,1,2,......42].

**Comment by sniper0110** [comment]
Thanks for indicating this. In fact, another person pointed this out in the comments. I'm glad you found a way to solve it.
